[local_addr]
ip = "127.0.0.1"
port = "9999"
[server_addr]
ip = "180.76.146.132"
port = "9998"

[convertor]
mode = "plaintext"
password = "Lh3TY2r5wxMvU89iHsjptXD72cIGAr0Q0O0DC5GFKICLTVTVDhhLIrA1cpCdc3uu2qTWu62/OFzF2F5pxzmX5oNbd7qfZrKs6+XSNMmJPEPXcQQXuF+BOpZ9xGz9MlE+vEFOygeo/jdIzLl8P4xlwRwnK4qh8LFg59FE//yOZOr0JOMA5Ihtr+Jaa+ybV08ay0cwMxmTt/GEGw9QWUU9FpjdTIbzAfrGfgqH9dtokr5/BSC2Jt5SCGG0KlZALe4hb83cjzY7o6mUpRRJCUoxnnZ4FULhle+mEiOrzuB5mY2cs1WgWA3f1HXyRilnpx9dwJoM+Kr2bvd0gnqiJREs6A=="

